config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('nutshell.urls')),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

nutshell/models.py
from django.db import models

class Category(models.Model):
    name = models.CharField(max_length=200, verbose_name="دسته")

    def __str__(self):
        return self.name


class Product(models.Model):
    name = models.CharField(max_length=200, verbose_name="عنوان محصول")
    price = models.IntegerField(verbose_name="قیمت محصول")
    quantity = models.PositiveIntegerField(verbose_name="چه مقدار(به گرم)")
    category = models.ForeignKey(Category, on_delete=models.CASCADE, verbose_name="دسته بندی")

    def __str__(self):
        return self.name


class City(models.Model):
    name = models.CharField(max_length=200, verbose_name="نام")

    def __str__(self):
        return self.name
    
class Inventory(models.Model):
    city = models.ForeignKey(City, on_delete=models.CASCADE, verbose_name="شهر")

    def __str__(self):
        return self.city.name

class InventoryProduct(models.Model):
    name = models.ForeignKey(Product, on_delete=models.CASCADE, verbose_name="نام")
    inventory = models.ForeignKey(Inventory, on_delete=models.CASCADE, verbose_name="انبار")
    quantity = models.PositiveIntegerField(blank=False, verbose_name="تعداد")

    def __str__(self):
        return self.name.name
    

from accounts.models import CustomUser
    
class Order(models.Model):
    username = models.ForeignKey(CustomUser, on_delete=models.CASCADE, verbose_name="خریدار")
    product = models.ForeignKey(InventoryProduct, on_delete=models.CASCADE, verbose_name="محصول")
    quantity = models.PositiveIntegerField(blank=False, verbose_name="تعداد")

    SUBMITTED = 'در حال آماده سازی'
    READY_TO_SEND = 'آماده ارسال'
    STATUS_CHOICES = [
        (SUBMITTED, 'در حال آماده سازی'),
        (READY_TO_SEND, 'آماده ارسال'),
    ]

    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default=SUBMITTED, verbose_name="وضعیت")

        

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    
      <title>NutShell</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    <script src="https://kit.fontawesome.com/your-font-awesome-kit.js" crossorigin="anonymous"></script>
    <script src="https://kit.fontawesome.com/63c4b57529.js" crossorigin="anonymous"></script>
    
  </head>
  <body dir="rtl">
    
    {% block nav %} {% endblock nav %}
    <script src="{% static 'jquery.js' %}"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/5.3.0/js/bootstrap.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.3/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"></script>
    <script src="{% static 'js/custom.js' %}"></script>
 
    <!-- persian numbers -->
 
 <script>
      persian = { 0: '۰', 1: '۱', 2: '۲', 3: '۳', 4: '۴', 5: '۵', 6: '۶', 7: '۷', 8: '۸', 9: '۹' };
      $(".persian-digit").each(function () {
        for (var i = 0; i <= 9; i++) {
          var re = new RegExp(i, "g");
          $(this).html($(this).html().replace(re, persian[i]));
        }
      });
    </script>
  </body>
</html>

templates/category.html
{% extends 'navs.html' %}

{% block content %}
<div class="p-5 my-3">
    <div class="d-flex">
        <div class="flex-grow-1 font-weight-bold h3 " style="color: sienna; text-align: right;">دسته بندی محصولات</div>
        <div class="flex-shrink-0">
            <a href="{% url 'category_new' %}" class="btn btn-success btn-square"><i class="fa-solid fa-plus h5"></i></a>
        </div>
    </div>

    <div class="table-responsive">
        <table class="table table-striped">
            <!-- head -->
            <thead>
                <tr>
                    <th>نام</th>
                    <th class="text-end">عملیات</th>
                </tr>
            </thead>
            <tbody>
                {% for category in object_list %}
                <!-- row 1 -->
                <tr>
                    <td>{{ category.name }}</td>
                    <td class="text-end"><a href="{% url 'category_delete' category.pk %}" class="btn btn-danger btn-square"><i class="fa-solid fa-trash-can"></i></a></td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>
{% endblock content %}

templates/category_new.html
{% extends 'navs.html' %}

{% block content %}
<div class="p-5 space-y-3">
    <h1 class="font-weight-bold fs-3 text-primary">دسته بندی جدید</h1> 
    <form action="" method="post">
        {% csrf_token %}
        <div class="form-group">
            {{ form }}
        </div>
        <input class="btn btn-success w-100 mt-3" type="submit" value="ذخیره">
    </form> 
</div>

{% endblock content %}

templates/city_delete.html
{% extends 'navs.html' %}

{% block content %}
<div class="p-5 space-y-3">
    <h1 class="font-weight-bold fs-3 text-primary">حذف شهر</h1> 
    <form action="" method="post">
        {% csrf_token %} 
        <p>آیا از حذف "{{ city.name }}" مطمئنید؟</p><br>
        <input type="submit" value="بله حذف شود" class="btn btn-danger w-100">
    </form> 
</div>
{% endblock content %}

templates/city_new.html
{% extends 'navs.html' %}

{% block content %}
<div class="p-5 space-y-3">
    <h1 class= "color: sienna; text-align: right;">شهر جدید</h1> 
    <form action="" method="post">
        {% csrf_token %}
        <div class="form-group">
            {{ form }}
        </div>
        <input class="btn btn-success w-100 mt-3" type="submit" value="ذخیره" style="background-color: peru;">
    </form> 
</div>

{% endblock content %}

templates/home.html
{% extends 'navs.html' %}
{% load static %}

{% block content %}
<style>
  .my-card {
    margin-bottom: 20px;
    background-color: #f8f9fa;
    border: none;
    border-radius: 10px;
    box-shadow: 0px 2px 10px rgba(0, 0, 0, 0.1);
    display: inline-block;
    width: calc(33.33% - 20px);
    vertical-align: top;
    margin-right: 10px;
    margin-top: 10px;
    box-sizing: border-box;
  }

  .my-card .card-body {
    padding: 1.5rem;
  }

  .my-card .card-title {
    font-weight: bold;
    font-size: 1.5rem;
    margin-bottom: 1rem;
  }

  .my-card p {
    font-size: 1rem;
    margin-bottom: 1.5rem;
  }

  .my-card .card-actions {
    display: flex;
    justify-content: flex-end;
  }

  .my-card .btn-primary {
    background-color: peru;
    border-color: peru;
    color: white;
  }

  .my-card .btn-primary:hover {
    background-color: sienna;
    border-color: sienna;
  }

  @media (max-width: 768px) {
    .my-card {
      width: 100%;
      margin-right: 0;
    }
  }

  .card-row {
    display: flex;
    flex-wrap: wrap;
    justify-content: center;
  }
</style>

{% if user.is_superuser %}
  <h1 class=" m-5 text-center fs-3">به پنل ادمین سایت ناتشل خوش آمدید</h1>
  <div class="mb-5">
    <div class="card-row">
      <div class="my-card">
        <div class="card-body">
          <h2 class="card-title fw-bold">دسته بندی</h2>
          <p>مشاهده و ویرایش دسته بندی محصولات</p>
          <div class="card-actions justify-content-end">
            <a href="{% url 'category' %}" class="btn btn-primary">مشاهده</a>
          </div>
        </div>
      </div>
      <div class="my-card">
        <div class="card-body">
          <h2 class="card-title fw-bold">محصولات</h2>
          <p>مشاهده و ویرایش انواع محصولات</p>
          <div class="card-actions justify-content-end">
            <a href="{% url 'product' %}" class="btn btn-primary">مشاهده</a>
          </div>
        </div>
      </div>
      <div class="my-card">
        <div class="card-body">
          <h2 class="card-title fw-bold">شهر ها</h2>
          <p>مشاهده و ویرایش شهر ها</p>
          <div class="card-actions justify-content-end">
            <a href="{% url 'city' %}" class="btn btn-primary">مشاهده</a>
          </div>
        </div>
      </div>
      <div class="my-card">
        <div class="card-body">
          <h2 class="card-title fw-bold">انبار ها</h2>
          <p>مشاهده و ویرایش انبار ها</p>
          <div class="card-actions justify-content-end">
            <a href="{% url 'inventory' %}" class="btn btn-primary">مشاهده</a>
          </div>
        </div>
      </div>
      <div class="my-card">
        <div class="card-body">
          <h2 class="card-title fw-bold">موجودی انبار ها</h2>
          <p>مشاهده و ویرایش موجودی انبار ها</p>
          <div class="card-actions justify-content-end">
            <a href="{% url 'inventoryProduct' %}" class="btn btn-primary">مشاهده</a>
          </div>
        </div>
      </div>
      <div class="my-card">
        <div class="card-body">
          <h2 class="card-title fw-bold">سفارش ها</h2>
          <p>مشاهده و ویرایش سفارش کاربران</p>
          <div class="card-actions justify-content-end">
            <a href="{% url 'order' %}" class="btn btn-primary">مشاهده</a>
          </div>
        </div>
      </div>
    </div>
  </div>
{% else %}
  <h1 class="font-extrabold m-5 text-center fs-3">به ناتشل خوش اومدی!</h1>
  <div class="card-row">
    {% for p in object_list %}
    <div class="my-card">
      <div class="card-body">
        <h2 class="card-title font-extrabold fs-1">{{ p.name }}</h2>
        <div class="persian-digit text-sm opacity-50 fw-bold">هر {{p.name.quantity}} گرم</div>
        {% if p.quantity > 0 %}
        <div class="persian-digit fw-bold text-success fs-2">{{ p.name.price }} تومان</div>
        {% else %}
        <div class="persian-digit fw-bold text-danger fs-2">ناموجود</div>
        {% endif %}

        <div class="card-actions justify-content-end">
          <a {% if p.quantity == 0 %} disabled {% endif %} href="{% url 'userOrder' p.pk %}" class="btn btn-primary w-100">خرید</a>
        </div>
      </div>
    </div>
    {% endfor %}
  </div>
{% endif %}

{% endblock content %}

templates/inventoryProduct_new.html
{% extends 'navs.html' %}

{% block content %}
<div class="p-5 space-y-3">
    <h1 class="font-bold text-3xl " style="color: sienna; text-align: right;">افزودن محصول جدید به انبار</h1> 
    <form action="" method="post">
        {% csrf_token %}
        <div class="form-group">
            {{ form }}
        </div>
        <input class="btn btn-success w-100 mt-3" type="submit" value="ذخیره">
    </form> 
</div>
{% endblock content %}

templates/inventory_delete.html
{% extends 'navs.html' %}
{% block content %} 
<div class="p-5 space-y-3">
<h1 class="font-bold text-3xl text-primary">حذف انبار</h1> 
<form action="" method="post">
    {% csrf_token %} 
    <p>آیا از حذف "{{ inventory.name }}" مطمئنید؟</p><br>
    <input type="submit" value="بله حذف شود" class="btn btn-danger w-100">
</form> 
</div>
{% endblock content %}

templates/order.html
{% extends 'navs.html' %}
{% block content %}
<div class="p-5">
    <div class="d-flex">
        <div class="flex-grow-1 font-weight-bold text-primary" style="font-size: 2rem;">سفارش کاربران</div>
    </div>

    <div class="table-responsive mt-3">
        <table class="table table-striped">
          <!-- head -->
          <thead>
            <tr>
              <th>سفارش دهنده</th>
              <th>انبار</th>
              <th>محصول</th>
              <th>تعداد</th>
              <th>وضعیت سفارش</th>
              <th class="text-end">عملیات</th>
            </tr>
          </thead>
          <tbody>
          {% for order in object_list %}
            <!-- row 1 -->
            <tr>
              <td>{{ order.username.username }}</td>
              <td>{{ order.product.inventory }}</td>
              <td>{{ order.product }}</td>
              <td class="persian-digit">{{ order.quantity }}</td>
              <td>{{ order.status }}</td>
              <td class="text-end">
                <a href="{% url 'order_update' order.pk %}" class="btn btn-warning btn-sm"><i class="fa fa-pen"></i></a>
                <a href="{% url 'order_delete' order.pk %}" class="btn btn-danger btn-sm"><i class="fa fa-trash"></i></a>
              </td>
            </tr>
          {% endfor %}
          </tbody>
        </table>
      </div>
</div>
{% endblock content %}

templates/order_delete.html
{% extends 'navs.html' %}
{% block content %}
<div class="p-5">
    <h1 class="font-weight-bold text-primary" style="font-size: 2rem;">حذف سفارش</h1> 
    <form action="" method="post">
        {% csrf_token %} 
        <p>آیا از حذف "{{ order.name }}" مطمئنید؟</p><br>
        <input type="submit" value="بله حذف شود" class="btn btn-danger w-100">
    </form> 
</div>
{% endblock content %}

templates/order_success.html
{% extends 'navs.html' %}
{% block content %} 
<div class="p-5 mt-5">
    <h1 class="font-weight-bold text-success text-center" style="font-size: 2rem;">خرید موفقیت آمیز بود</h1> 
 
    <p class="text-center">خرید شما با موفقیت ثبت شد و وضعیت آن قسمت پیگیری خرید قابل مشاهده است.</p><br>
    <a href="{% url 'home' %}" class="btn btn-primary w-100">بازگشت</a>
 
</div>
{% endblock content %}

templates/product_delete.html
{% extends 'navs.html' %}

{% block content %}
<div class="p-5 space-y-3">
    <h1 class="font-bold text-3xl text-primary">حذف محصول</h1> 
    <form action="" method="post">
        {% csrf_token %} 
        <p>آیا از حذف "{{ product.name }}" مطمئنید؟</p><br>
        <button type="submit" class="btn btn-danger btn-block">بله حذف شود</button>
    </form> 
</div>
{% endblock content %}

templates/product_new.html
{% extends 'navs.html' %}

{% block content %}
<style>
  .form-container {
    display: flex;
    flex-wrap: wrap;
    justify-content: flex-start;
    text-align: right;
    gap: 1rem;
  }

  .form-container label {
    color: peru;
  }

  .form-container input[type="text"],
  .form-container textarea {
    width: 300px; /* Set a fixed width for the input fields */
    border: 1px solid peru;
    border-radius: 5px;
    padding: 0.5rem;
    box-sizing: border-box;
  }

  .form-container button {
    background-color: peru;
    border: none;
    color: white;
    border-radius: 5px;
    padding: 0.75rem 1rem;
    font-weight: bold;
    font-size: 1.2rem;
  }

  .form-container button:hover {
    background-color: sienna;
  }

  .form-heading {
    color: sienna;
    font-weight: bold;
    font-size: 2rem;
    text-align: right;
  }
</style>

<div class="p-5">
    <h1 class="form-heading">محصول جدید</h1> 
    <br>
    <form action="" method="post" class="form-container">
        {% csrf_token %}

        <div>
            <label for="id_name">نام:</label>
            {{ form.name }}
        </div>
        <div>
            <label for="id_price">قیمت:</label>
            {{ form.price }}
        </div>
        <div>
            <label for="id_quantity">تعداد:</label>
            {{ form.quantity }}
        </div>

        <br>
        <button type="submit">ذخیره</button>
    </form> 
</div>
{% endblock content %}

templates/userOrderList.html
{% extends 'navs.html' %}

{% block content %}
<div class="p-5">
    
    <div class="font-weight-bold text-3xl text-primary">سفارشات شما</div>
        
    <div class="table-responsive">
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>محصول</th>
                    <th>تعداد</th>
                    <th>وضعیت</th>
                </tr>
            </thead>
            <tbody>
                {% for p in object_list %}
                <tr>
                    <td>{{ p.product.name }}</td>
                    <td>{{ p.quantity }}</td>
                    <td>{{ p.status }}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
    
</div>
{% endblock content %}